name: Deploy with Submodule

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          #!/bin/bash

          PROJECT_DIR="/var/www"

          mkdir -p "$PROJECT_DIR"
          cd "$PROJECT_DIR" || exit 1

          rm -rf "$PROJECT_DIR"/*

    - name: Sync code to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        source: "."
        target: "/var/www"

    - name: Run docker-compose on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          cd /var/www
          if command -v docker &> /dev/null && docker compose version &> /dev/null; then
            COMPOSE_CMD="docker compose"
          elif command -v docker-compose &> /dev/null; then
            COMPOSE_CMD="docker-compose"
          else
            echo "error not install docker"
            exit 1
          fi

          $COMPOSE_CMD -f docker-compose.yml down
          $COMPOSE_CMD -f docker-compose.yml up -d --build
